### ISSUE TITLE
Fatal error: Uncaught Error: Using $this when not in object context in

### ISSUE THREAD

**Issue by tiagocaus** [mitmelon/Compress#3]
Fatal error: Uncaught Error: Using $this when not in object context in

PHP 8.1

```
<?php
require __DIR__ . "/../bootstrap.php";

$compress = new Compress\Compress;

$compress::compressFile(__DIR__.'/original.pdf', __DIR__.'/original.compress.pdf', true);
```

**Comment by mitmelon** [comment]
At what line are you getting this error from. If you can show me your code then I will be able to debug this better.

**Comment by mitmelon** [comment]
> Fatal error: Uncaught Error: Using $this when not in object context in

At what line are you getting this error from. If you can show me your code then I will be able to debug this better.

**Comment by tiagocaus** [comment]
> At what line are you getting this error from. If you can show me your code then I will be able to debug this better.

PHP 8.1

```
<?php
require __DIR__ . "/../bootstrap.php";

$compress = new Compress\Compress;

$compress::compressFile(__DIR__.'/original.pdf', __DIR__.'/original.compress.pdf', true);
```

**Comment by ahmed-mohammed2** [comment]
I have the same problem.
any updates

**Comment by mitmelon** [comment]
Let me try to reproduce this error... Will update this issue soon. Thanks.

**Comment by mitmelon** [comment]
> Let me try to reproduce this error... Will update this issue soon. Thanks.

Please update compress  to the bug fix. I have corrected and fixed the issue.

Please do let me know if any bug arises again. Thank u.

**Comment by tiagocaus** [comment]
@mitmelon has packagist been updated?

**Comment by mitmelon** [comment]
> @mitmelon has packagist been updated?

Thanks for the remembrance... I have just updated it...

**Comment by tiagocaus** [comment]
@mitmelon Not up to date yet https://packagist.org/packages/mitmelon/compress

**Comment by tiagocaus** [comment]
@mitmelon packagist is not updated yet.
