### ISSUE TITLE
Decompressed content show PHP serialization element

### ISSUE THREAD

**Issue by ppazos** [mitmelon/Compress#7]
I think this line introduces a string element in the compressed contents https://github.com/mitmelon/Compress/blob/9db1fe3a6d683dfa7d03b680b8f6ca030af81473/Compress/Compress.php#L89

The issue is that appears in the decompressed contents, check the s:13517102" at the beginning and the "; at the end of the uncompressed content that makes the output different from the input.

![Screenshot_2023-11-01_13-50-15](https://github.com/mitmelon/Compress/assets/1278556/7a214bd8-4a07-4ea9-ba26-191ab1601688)

![Screenshot_2023-11-01_13-50-48](https://github.com/mitmelon/Compress/assets/1278556/89fe0d7b-1d7c-4641-b484-8f4b7ebc7151)

Is the serialize() needed there?

Note: the decompress from this library doesn't seem to show that extra data, but an independent tool was used to decompress for verification https://unix.stackexchange.com/questions/22834/how-to-uncompress-zlib-data-in-unix/240060#240060

**Comment by mitmelon** [comment]
> I think this line introduces a string element in the compressed contents
> 
> https://github.com/mitmelon/Compress/blob/9db1fe3a6d683dfa7d03b680b8f6ca030af81473/Compress/Compress.php#L89
> 
> The issue is that appears in the decompressed contents, check the s:13517102" at the beginning and the "; at the end of the uncompressed content that makes the output different from the input.
> 
> ![Screenshot_2023-11-01_13-50-15](https://user-images.githubusercontent.com/1278556/279749532-7a214bd8-4a07-4ea9-ba26-191ab1601688.png)
> 
> ![Screenshot_2023-11-01_13-50-48](https://user-images.githubusercontent.com/1278556/279749557-89fe0d7b-1d7c-4641-b484-8f4b7ebc7151.png)
> 
> Is the serialize() needed there?
> 
> Note: the decompress from this library doesn't seem to show that extra data, but an independent tool was used to decompress for verification https://unix.stackexchange.com/questions/22834/how-to-uncompress-zlib-data-in-unix/240060#240060

Yes the serialize needs to be there to make the data much more smaller. Using another decompress tool for the data won't work.

You will have to use the one provided from compress library.

Please note that both the compressor and decompressor function is not a generalized implementations. Whatever you compress with this library must also be decompressed back with same library.

Hope this solves your case?

**Comment by ppazos** [comment]
Thanks @mitmelon one question, isn't serialize a method just to serialize PHP objects? https://www.php.net/manual/en/function.serialize.php

I'm not sure how serialize() applies for any other content than PHP objects. If you check the images I sent, it just considers the whole content as a huge string, then the content itself is unchanged. In my case I'm compressing SQL.

**Comment by mitmelon** [comment]
> Thanks @mitmelon one question, isn't serialize a method just to serialize PHP objects? https://www.php.net/manual/en/function.serialize.php
> 
> I'm not sure how serialize() applies for any other content than PHP objects. If you check the images I sent, it just considers the whole content as a huge string, then the content itself is unchanged. In my case I'm compressing SQL.

Yes you are right. Majorly the serialize are meant for image objects or binary. Like in your case now, you are compressing a normal string which makes serialize useless.

I think what I will have to do is to detect what type of contents are passed first to predict either to use serialize on it or not... Then add more minimizing implementations such as space removal, comments and so on.

I will work on that probably next month because I have a project to kick off...

However if you wish to help... You can create a pull request and I will merge.

Thanks for the clarifications... It will be great to know more about you. May be we could do great things together.

**Comment by ppazos** [comment]
Thanks @mitmelon I'll test what happens by removing the serialize() for my SQL case and will use a different tool to uncompress the zlib result. I believe that result will be correct with the zlib format, so uncompressing won't need to to unserialize in the uncompress https://github.com/mitmelon/Compress/blob/master/Compress/Compress.php#L109C25-L109C36

I also believe that won't affect the size of the output. I'll test and get to you ASAP, hopefully with a PR.

**Comment by mitmelon** [comment]
> Thanks @mitmelon I'll test what happens by removing the serialize() for my SQL case and will use a different tool to uncompress the zlib result. I believe that result will be correct with the zlib format, so uncompressing won't need to to unserialize in the uncompress https://github.com/mitmelon/Compress/blob/master/Compress/Compress.php#L109C25-L109C36
> 
> I also believe that won't affect the size of the output. I'll test and get to you ASAP, hopefully with a PR.

Thank you very much and hoping to see your PR.

**Comment by mitmelon** [comment]
![flashdrive](https://github.com/mitmelon/Compress/assets/55149512/d566ece6-41c3-4d25-9aae-d9bca05570f6)
