### ISSUE TITLE
Decompressed file is truncated to 100MB

### ISSUE THREAD

**Issue by ppazos** [mitmelon/Compress#9]
Hi, I'm checking some large files I'm compressing using this library. I have 800+MB files and the compressed one is about 60MB which seemed OK. Then I use the zlib-flate command to uncompress (https://www.mankier.com/1/zlib-flate) and I get a 100MB file back, which is a truncated version of the original 800+MB file.

I did the test of using zlib-flate to compress and uncompress and I'm getting the same file back, so I think there is something with the compress step from this library that might be cutting the data at 100MB.

Is that possible?

Thanks.

**Comment by mitmelon** [comment]
> Hi, I'm checking some large files I'm compressing using this library. I have 800+MB files and the compressed one is about 60MB which seemed OK. Then I use the zlib-flate command to uncompress (https://www.mankier.com/1/zlib-flate) and I get a 100MB file back, which is a truncated version of the original 800+MB file.
> 
> I did the test of using zlib-flate to compress and uncompress and I'm getting the same file back, so I think there is something with the compress step from this library that might be cutting the data at 100MB.
> 
> Is that possible?
> 
> Thanks.

First what type of file type are you compressing?

**Comment by ppazos** [comment]
it's SQL so it's just plain text but it's 800+MB

**Comment by ppazos** [comment]
@mitmelon maybe this has something to do with the issue: https://github.com/mitmelon/Compress/blob/e64f4de92cf77c96c7d4bf6484a11199041e5cce/Compress/Compress.php#L26

**Comment by mitmelon** [comment]
> @mitmelon maybe this has something to do with the issue:
> 
> https://github.com/mitmelon/Compress/blob/e64f4de92cf77c96c7d4bf6484a11199041e5cce/Compress/Compress.php#L26

Ooohh... I see... The $compress_chunk_size is public just adjust it to lowest value... Use 5 or 10 instead of 100 and see if it still truncates some data.

**Comment by ppazos** [comment]
@mitmelon will retest ASAP

**Comment by ppazos** [comment]
@mitmelon I can confirm that changing the $compress_chunk_size determines the size of the decompressed file though it doesn't affect the size of the compressed file.

1. I changed the chunk to be 100 KB // public int $compress_chunk_size = 100 * 1024;
2. Did the compress and the generated file was 60MB (this size makes sense since the original file is 800+MB)
3. The uncompressed file is 100KB !!!

I believe there is something between chunks that makes the uncompress not work, maybe detecting that as an EOF or something with the gzcompress algorithm that might need to compress one chunk instead of many?

`$compressed_chunk = $this->complex_compress(gzcompress($chunk, 9));`

Looking at the gzcompress documentation it doesn't say anything about the support for compressing in chunks, so for input data that is larger than the chunk, the uncompressed file will always be truncated if a different library is used for uncompressing the file or even if the same library is used but have different chunk sizes for compressing and decompressing. That is a deal breaker for our use case, sorry.

**Comment by mitmelon** [comment]
> @mitmelon I can confirm that changing the $compress_chunk_size determines the size of the decompressed file though it doesn't affect the size of the compressed file.
> 
> 1. I changed the chunk to be 100 KB // public int $compress_chunk_size = 100 * 1024;
> 2. Did the compress and the generated file was 60MB (this size makes sense since the original file is 800+MB)
> 3. The uncompressed file is 100KB !!!
> 
> I believe there is something between chunks that makes the uncompress not work, maybe detecting that as an EOF or something with the gzcompress algorithm that might need to compress one chunk instead of many?
> 
> `$compressed_chunk = $this->complex_compress(gzcompress($chunk, 9));`
> 
> Looking at the gzcompress documentation it doesn't say anything about the support for compressing in chunks, so for input data that is larger than the chunk, the uncompressed file will always be truncated if a different library is used for uncompressing the file or even if the same library is used but have different chunk sizes for compressing and decompressing. That is a deal breaker for our use case, sorry.

Ooohhh I see... I will look into this probably soon and correct it. But my solar system is having issues and don't have the funds to get the repaired right now. As soon as am able to have funds to get it repaired, I will work on it again and this time provide more sophisticated compressing approach that really works.

Thanks for your notice... I appreciate your efforts ... 🫂
